// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAltRbUwBvlCOp5U-TFRFXGpEJut6txHzQ',
    appId: '1:821491385956:web:397b35c255707573748171',
    messagingSenderId: '821491385956',
    projectId: 'alsanafer-15719',
    authDomain: 'alsanafer-15719.firebaseapp.com',
    storageBucket: 'alsanafer-15719.appspot.com',
    measurementId: 'G-3V88TDL215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91EZNGtu0Wc6EO6oLXwIxM5gs2_pQPmQ',
    appId: '1:821491385956:android:719662a4241573e0748171',
    messagingSenderId: '821491385956',
    projectId: 'alsanafer-15719',
    storageBucket: 'alsanafer-15719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLd7oLuj4WAKWYhh9ltMf30d7Mv1GFYM',
    appId: '1:821491385956:ios:16b213f09f7c2945748171',
    messagingSenderId: '821491385956',
    projectId: 'alsanafer-15719',
    storageBucket: 'alsanafer-15719.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnLd7oLuj4WAKWYhh9ltMf30d7Mv1GFYM',
    appId: '1:821491385956:ios:16b213f09f7c2945748171',
    messagingSenderId: '821491385956',
    projectId: 'alsanafer-15719',
    storageBucket: 'alsanafer-15719.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAltRbUwBvlCOp5U-TFRFXGpEJut6txHzQ',
    appId: '1:821491385956:web:52afbc6bebf252fd748171',
    messagingSenderId: '821491385956',
    projectId: 'alsanafer-15719',
    authDomain: 'alsanafer-15719.firebaseapp.com',
    storageBucket: 'alsanafer-15719.appspot.com',
    measurementId: 'G-JJVENY3JNB',
  );

}